id: PA6676F62
initial_creation_type: input
source_metadata:
  Title: Bodhicaryāvatāra of Śāntideva with the Commentary Panjika of Prajnakaramati
  Editor: ''
  Publisher: ''
  Place of Publication: ''
  Year: ''
  १ बोधिचित्तानुशंसो नाम प्रथमः परिच्छेदः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  २ पापदेशना नाम द्वितीयः परिच्छेदः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  ३ बोधिचित्तपरिग्रहो नाम तृतीयः परिच्छेदः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  ४ बोधिचित्ताप्रमादो नाम चतुर्थः परिच्छेदः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  ५ संप्रजन्यरक्षणं नाम पञ्चमः परिच्छेदः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  ६ क्षान्तिपारमिता नाम षष्ठः परिच्छेदः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  ७ वीर्यपारमिता नाम सप्तमः परिच्छेदः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  ८ ध्यानपारमिता नाम अष्टमः परिच्छेदः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  ९ प्रज्ञापारमिता नाम नवमः परिच्छेदः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  १० परिणामनापरिच्छेदो दशमः:
    Text Version: Devanāgarī
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T17:00:28.101286'
last_modified_at: '2022-03-08T17:00:28.101297'
